name: Build
on:
    push:
      branches: [ master ]

env:
  FLUTTER_CHANNEL: "stable"

jobs:
    build:    
        runs-on: ${{ matrix.os }}

        strategy:
          matrix:
            os: [ ubuntu-latest ]
            target: [ web, linux ]

        steps:
          - name: Build path
            id: get_path
            run: |
              if ["${{ matrix.target }}" == "linux"]
              then
                  echo "::set-output name=path::build/linux/x64/release/bundle"
              else
                  echo "::set-output name=path::build/web"
              fi

          - uses: subosito/flutter-action@v2
            with:
              channel: "$FLUTTER_CHANNEL"

          - name: Checkout code
            uses: actions/checkout@v3

          - name: Fetch dependencies
            run: flutter pub get

          - name: Install Linux requirements
            if: matrix.target == 'linux'
            run: apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

          - name: Build for ${{ matrix.target }}
            run: flutter build ${{ matrix.target }}

          - name: Upload ${{ matrix.target }} artifact
            uses: actions/upload-artifact@v2
            with:
                name: foreplay-${{ matrix.target }}
                path: ${{ steps.get_path.outputs.path }}

    build-windows:
        runs-on: windows-latest

        steps:
          - uses: subosito/flutter-action@v2
            with:
              channel: "$FLUTTER_CHANNEL"

          - name: Checkout code
            uses: actions/checkout@v3

          - name: Fetch dependencies
            run: flutter pub get

          - name: Build for Windows
            run: flutter build windows

          - name: Upload Windows
            uses: actions/upload-artifact@v2
            with:
                name: foreplay-windows
                path: build/windows/runner/Release